apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.imagePullSecrets.name }}"
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  {{ .Values.imagePullSecrets.key }}: {{ .Values.imagePullSecrets.value }}
type: {{ .Values.imagePullSecrets.type }} 