apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLkNBRVNJTC1OM0c4YkFMSjJjanVoZUU3eTlyWl9pUzFQd25YQkQ1a2lHY3I1UGVUUUdoNEtIR2gyY3k1Uk5sQk5URTlhVUVGS1IxWlhhMmhaVURsSGVIcE1iVlE=
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson 
