apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.mongoSecrets.name }}"
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
data:
  {{ .Values.mongoSecrets.key }}: {{ .Values.mongoSecrets.value }}
type: {{ .Values.mongoSecrets.type }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.imagePullSecrets.name }}"
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
data:
  {{ .Values.imagePullSecrets.key }}: {{ .Values.imagePullSecrets.value }}
type: {{ .Values.imagePullSecrets.type }} 
