apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      server {

        listen 8080;

        location / {
          root   /usr/share/nginx/html;
          index  index.html;
          try_files $uri $uri/ /index.html;
        }

        location /api {
            proxy_pass http://backend:8080;
        }
      }
    }
