apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.vaultSecrets.name }}"
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{ .Values.vaultSecrets.key }}: {{ .Values.vaultSecrets.value }}
type: {{ .Values.vaultSecrets.type }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.imagePullSecrets.name }}"
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{ .Values.imagePullSecrets.key }}: {{ .Values.imagePullSecrets.value }}
type: {{ .Values.imagePullSecrets.type }} 
