version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    volumes:
      - ~/minio/data:/data:rw
    networks:
      - internal    
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ""
      MINIO_ROOT_PASSWORD: ""
    command:
      "server /data --console-address \":9090\""

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/sausage-minio.ru.crt:/etc/ssl/certs/sausage-minio.ru.crt:ro
      - /etc/ssl/private/sausage-minio.ru.key:/etc/ssl/private/sausage-minio.ru.key:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    networks:
      - internal  
    ports:
      - 443:443

networks:
  internal: